---
{{- if not .Values.dev -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-clusterrole
  labels:
    relaxdiego.com: prometheus-operator
rules:
  - apiGroups: [""]
    resources: ["configmaps", "services"]
    verbs: ["get", "create", "delete"]

    # Helm uses secrets to manage release information
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "get", "create", "update", "patch", "delete"]

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "create", "patch", "delete"]

  - apiGroups: ["relaxdiego.com"]
    resources: ["prometheusclusters"]
    verbs: ["watch"]
{{- end -}}
