{{- if and (.Values.serviceAccount.create) (not .Values.dev) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-operator.serviceAccountName" . }}
  labels:
{{ include "prometheus-operator.labels" . | nindent 4 }}
    relaxdiego.com: prometheus-operator
{{- end -}}
