---
# Real service that load balances between pods
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-cluster
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
