apiVersion: v1
kind: Config
clusters:
- name: cluster
  cluster:
    certificate-authority-data: {{ca_crt}}
    server: {{server_addr}}
contexts:
- name: context
  context:
    cluster: cluster
    namespace: {{namespace}}
    user: user
users:
- name: user
  user:
    token: {{token}}
current-context: context
