---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-clusterrolebinding
  labels:
    relaxdiego.com: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "prometheus-operator.serviceAccountName" . }}
  namespace: {{ .Chart.Name }}
